# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-10 02:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cnapWithType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peopleCounter', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='historyOfRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queueapi.cnapWithType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='infoAboutCnap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('adress', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='typeOfCnap',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=220)),
            ],
        ),
        migrations.AddField(
            model_name='cnapwithtype',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queueapi.typeOfCnap'),
        ),
        migrations.AddField(
            model_name='cnapwithtype',
            name='znap_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queueapi.infoAboutCnap'),
        ),
    ]
