# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-10 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeofcnap',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
