# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-19 14:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueapi', '0002_auto_20171119_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnapwithservice',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 19, 16, 21, 38, 158000)),
        ),
    ]
