# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-23 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationToZnap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('znap', models.CharField(max_length=124)),
                ('date', models.CharField(max_length=124)),
                ('time', models.CharField(max_length=124)),
                ('service', models.CharField(max_length=226)),
                ('html', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapi.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Znap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
