# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0007_admin_znap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='io',
        ),
    ]
