# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-24 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='user_id',
            new_name='user',
        ),
    ]
