# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 16:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0002_auto_20171024_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='timeStamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 25, 19, 50, 36, 426000)),
        ),
    ]
