# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 17:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0003_auto_20171025_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='rate',
            name='timeStamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 25, 20, 0, 25, 915000)),
        ),
    ]
