# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 17:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0011_auto_20171025_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='timeStamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 25, 20, 13, 27, 97000)),
        ),
    ]
