# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 17:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0016_auto_20171025_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='timeStamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 25, 20, 19, 9, 278000)),
        ),
    ]
