# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 07:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0022_auto_20171025_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='rate',
        ),
        migrations.AlterField(
            model_name='rate',
            name='timeStamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 1, 9, 17, 1, 139000)),
        ),
    ]
