# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 10:55
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userapi', '0023_auto_20171101_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('dialogID', models.IntegerField()),
                ('timeStamp', models.DateTimeField(default=datetime.datetime(2017, 11, 2, 12, 55, 29, 313000))),
                ('typef', models.CharField(choices=[('1', '1')], max_length=1)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapi.Admin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='rate',
            name='timeStamp',
        ),
    ]
