# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 10:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0024_auto_20171102_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='admin',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='userapi.Admin'),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='timeStamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 2, 12, 56, 35, 43000)),
        ),
    ]
